import { Activity, ArrowRight, CreditCard, Mail, MessageSquare, ShieldCheck, Users, Wallet, Zap, CircleCheck, Clock3, TrendingUp, Plus, ArrowUpRight } from 'lucide-react';

const services = [
  { id: 'sms-otp-dashboard', name: 'SMS & OTP', desc: 'OTP, transactional and bulk messaging', icon: MessageSquare, status: 'Operational', color: 'blue' },
  { id: 'email-otp', name: 'Email', desc: 'Transactional and OTP email delivery', icon: Mail, status: 'Operational', color: 'violet' },
  { id: 'whatsapp', name: 'WhatsApp', desc: 'Business messaging and templates', icon: MessageSquare, status: 'Setup needed', color: 'emerald' },
  { id: 'voice', name: 'Voice', desc: 'Voice OTP and calling APIs', icon: Activity, status: 'Setup needed', color: 'amber' },
  { id: 'kyc', name: 'KYC verification', desc: 'Identity and verification workflows', icon: ShieldCheck, status: 'Coming soon', color: 'slate' },
  { id: 'payments', name: 'Payments', desc: 'Payment gateway and collections', icon: CreditCard, status: 'Coming soon', color: 'rose' },
];
const stats = [
  { label: 'API requests today', value: '16,730', change: '+8.4%', note: 'vs previous day', icon: Activity },
  { label: 'Success rate', value: '98.7%', change: '+1.2%', note: 'vs previous day', icon: CircleCheck },
  { label: 'Active services', value: '2', change: 'of 6', note: 'services configured', icon: Zap },
  { label: 'Wallet balance', value: '₹84,520', change: 'Healthy', note: 'available balance', icon: Wallet },
];
const bars = [32,45,38,62,53,70,48,82,61,74,56,88,65,78,54,92,68,80,60,72,48,85,66,96,73,82,58,77];

export default function Home({ onSelect }) {
  return <main className="min-w-0 flex-1 bg-[#f5f7fb] p-4 md:p-7">
    <div className="mx-auto max-w-[1500px] space-y-6">
      <section className="flex flex-col gap-4 rounded-2xl bg-gradient-to-r from-[#10234a] via-[#173b77] to-[#2459ad] p-5 text-white shadow-sm md:flex-row md:items-center md:justify-between md:p-7">
        <div><div className="flex items-center gap-2 text-xs font-medium text-blue-100"><span className="h-2 w-2 rounded-full bg-emerald-400"/> SERVICE CONSOLE</div><h1 className="mt-3 text-2xl font-bold tracking-tight md:text-3xl">Your services, at a glance.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-blue-100">Monitor API activity, manage integrations and get to the tools you need without the clutter.</p></div>
        <button onClick={() => onSelect('user-setup')} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-blue-900 shadow-sm transition hover:bg-blue-50"><Plus size={17}/> Set up profile <ArrowRight size={16}/></button>
      </section>
      <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 2xl:grid-cols-4">{stats.map(({label,value,change,note,icon:Icon})=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon size={19}/></span></div><div className="mt-4 flex items-center gap-2 text-xs"><span className="font-semibold text-emerald-700">{change}</span><span className="text-slate-400">{note}</span></div></article>)}</section>
      <section className="grid gap-5 2xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,0.8fr)]">
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Service workspace</h2><p className="mt-1 text-xs text-slate-500">Open a service to manage its settings and activity.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">6 services</span></div><div className="grid gap-3 p-4 sm:grid-cols-2">{services.map(({id,name,desc,icon:Icon,status,color})=><button key={id} onClick={() => onSelect(id)} className="group rounded-xl border border-slate-200 p-4 text-left transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div className="flex items-start justify-between"><span className={'grid h-10 w-10 place-items-center rounded-xl '+(color==='blue'?'bg-blue-50 text-blue-700':color==='violet'?'bg-violet-50 text-violet-700':color==='emerald'?'bg-emerald-50 text-emerald-700':color==='amber'?'bg-amber-50 text-amber-700':color==='rose'?'bg-rose-50 text-rose-700':'bg-slate-100 text-slate-600')}><Icon size={20}/></span><ArrowUpRight size={17} className="text-slate-300 transition group-hover:text-blue-600"/></div><h3 className="mt-4 text-sm font-semibold text-slate-900">{name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-slate-500">{desc}</p><div className="mt-3 flex items-center gap-2 border-t border-slate-100 pt-3"><span className={'h-1.5 w-1.5 rounded-full '+(status==='Operational'?'bg-emerald-500':status==='Setup needed'?'bg-amber-500':'bg-slate-400')}/><span className="text-[11px] text-slate-500">{status}</span></div></button>)}</div></div>
        <div className="space-y-5">
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">API traffic</h2><p className="mt-1 text-xs text-slate-500">Request volume · last 24 hours</p></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700">+8.4%</span></div><div className="mt-6 flex h-32 items-end gap-1.5">{bars.map((height,index)=><div key={index} title={'Activity '+(index+1)} className="flex-1 rounded-t-sm bg-blue-500/80 transition hover:bg-blue-700" style={{height:height+'%'}}/>)}</div><div className="mt-3 flex justify-between text-[10px] text-slate-400"><span>12 AM</span><span>6 AM</span><span>12 PM</span><span>6 PM</span><span>Now</span></div></section>
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-900">Quick actions</h2><Zap size={17} className="text-blue-600"/></div><div className="mt-3 space-y-2">{[{label:'Configure profile & API',sub:'Contact details and 2Factor credentials',id:'user-setup',icon:Users},{label:'Open SMS dashboard',sub:'Delivery overview and recent activity',id:'sms-otp-dashboard',icon:MessageSquare},{label:'Manage API keys',sub:'Credentials and integration settings',id:'sms-otp-api',icon:ShieldCheck}].map(({label,sub,id,icon:Icon})=><button key={id} onClick={()=>onSelect(id)} className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left transition hover:border-blue-200 hover:bg-blue-50/60"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-700"><Icon size={17}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-slate-800">{label}</span><span className="mt-0.5 block text-xs text-slate-500">{sub}</span></span><ArrowRight size={15} className="text-slate-400"/></button>)}</div></section>
          <section className="rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-blue-700"><TrendingUp size={18}/></span><div><h3 className="text-sm font-semibold text-slate-900">Keep your setup healthy</h3><p className="mt-1 text-xs leading-5 text-slate-600">Add your profile and API credentials to prepare your console for service integrations.</p><button onClick={()=>onSelect('user-setup')} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-700 hover:text-blue-900">Complete setup <ArrowRight size={14}/></button></div></div></section>
        </div>
      </section>
      <p className="text-[11px] text-slate-400">Dashboard metrics shown here are sample UI values until live analytics APIs are connected.</p>
    </div>
  </main>;
}
